# Generated by Django 6.0.1 on 2026-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cd_list_id',
            field=models.CharField(blank=True, help_text="cd_list_id (UUID) in the external call-centre database used to scope 'Sync from database' pulls for this campaign", max_length=64, null=True),
        ),
    ]
