# Generated by Django 6.0.1 on 2026-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_campaign_cd_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='cd_list_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cd_campaign_id',
            field=models.CharField(blank=True, help_text="Campaign UUID (cxm.campaigns.id) in the external call-centre database used to scope 'Sync from database' pulls", max_length=64, null=True),
        ),
    ]
