# Generated by Django 6.0.1 on 2026-07-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_campaign_cd_list_id_campaign_cd_campaign_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='outcome_set',
            field=models.ForeignKey(blank=True, help_text="Outcome set this campaign's uploads/syncs resolve descriptions against", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dashboard.outcomeset'),
        ),
        migrations.AddField(
            model_name='outcomedescription',
            name='outcome_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='dashboard.outcomeset'),
        ),
    ]
