# Generated by Django 6.0.1 on 2026-07-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_default_outcome_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='QACallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('recording_key', models.CharField(blank=True, max_length=500, null=True)),
                ('recording_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_records', to='dashboard.campaign')),
            ],
            options={
                'ordering': ['-call_date'],
                'indexes': [models.Index(fields=['campaign', 'call_date'], name='dashboard_q_campaig_0a2b32_idx'), models.Index(fields=['campaign', 'outcome'], name='dashboard_q_campaig_561921_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'contact_id'), name='unique_qa_record_per_contact')],
            },
        ),
    ]
