# Generated by Django 5.2.9 on 2026-09-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_qacallrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, help_text='Campaign end date from external source', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When campaign metadata was last synced from external source', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Campaign start date from external source', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cd_campaign_id',
            field=models.CharField(blank=True, db_index=True, help_text="Campaign UUID (cxm.campaigns.id) in the external call-centre database used to scope 'Sync from database' pulls", max_length=64, null=True, unique=True),
        ),
    ]
