# Generated by Django 6.0.1 on 2026-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_qacallrecord_interaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
