# Generated by Django 6.0.1 on 2026-10-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_processeddata_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QASyncWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_sync_windows', to='dashboard.campaign')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['campaign', 'start'], name='dashboard_q_campaig_ad17f7_idx')],
            },
        ),
    ]
