# Generated by Django 6.0.1 on 2026-10-05 17:53

from django.db import migrations, models


def forget_synced_windows(apps, schema_editor):
    """
    Rows already in QACallRecord don't have the new download columns. Clearing
    the recorded sync windows makes the QA page flag those ranges as unsynced
    ("Sync missing range"), and re-syncing upserts the new columns in place.
    """
    apps.get_model('dashboard', 'QASyncWindow').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_qasyncwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacallrecord',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='call_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='lead_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='talk_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forget_synced_windows, migrations.RunPython.noop),
    ]
