# Generated by Django 6.0.1 on 2026-10-05 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forget_synced_windows(apps, schema_editor):
    """Cached rows lack the new Extension / Hangup User values; clearing the
    recorded sync windows makes the QA page flag them for a re-sync (see 0011)."""
    apps.get_model('dashboard', 'QASyncWindow').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_qacallrecord_download_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qacallrecord',
            name='extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qacallrecord',
            name='hangup_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='QAActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sync', 'Sync'), ('download', 'Download')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='running', max_length=10)),
                ('campaign_label', models.CharField(blank=True, default='', max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('records', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='qa_activity/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_q_user_id_2969da_idx')],
            },
        ),
        migrations.RunPython(forget_synced_windows, migrations.RunPython.noop),
    ]
