# Generated by Django 6.0.1 on 2026-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_qa_activity_extension_hangup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('Floor 1', 'Floor 1'), ('Floor 2', 'Floor 2')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('source_team_names', models.JSONField(blank=True, default=list, help_text='Exact reporting.teams names (e.g. ["TeamSbu"]). Leave empty until mapped — the row shows zeros.')),
                ('target', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['floor', 'sort_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('floor', 'display_name'), name='unique_dashboard_team_per_floor')],
            },
        ),
    ]
